name: Build & Deploy


on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

  schedule:
    # Nightly builds
    - cron: '0 2 * * *'

jobs:

  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Build the site
        run: php hyde build --no-interaction

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs'
          message: 'Build & Deploy: ${{ github.sha }}'
